# Generated by Django 4.0.5 on 2022-11-15 11:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('body', tinymce.models.HTMLField()),
                ('nextpage', tinymce.models.HTMLField()),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(default='NA', max_length=250)),
                ('pincode', models.CharField(default='NA', max_length=20)),
                ('phone', models.CharField(default='NA', max_length=30)),
                ('rating', models.FloatField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='db.blog')),
            ],
        ),
    ]
