# Generated by Django 4.0.5 on 2022-11-15 12:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='nextpage',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
